socket_params:
  ip_address: '192.168.0.1'        # IP‑адрес контроллера Robotino
  port: 80                         # Порт TCP‑соединения
  enable: 1                        # Подключение к роботу (0 - без подключения, 1 - с подключением)

camera:
  H: 290.0                         # Высота установки камеры над плоскостью пола (только при parallax = 1)
  h: 24.3                          # Высота препятствия (только при parallax = 1)
  offset_x: -200                   # Смещение центра кадра по оси X (только при parallax = 1)
  offset_y: -150                   # Смещение центра кадра по оси Y (только при parallax = 1)
  wall_width: 200                  # Ширина виртуальной стены по краям рабочей области
  add_zone_green: 20               # Дополнительный отступ для препятствия
  add_zone_red: 20                 # Дополнительный отступ для препятствия
  add_zone_blue: 20
  scale_factor: 0.2                # Масштабный коэффициент для уменьшения параллакс изображения
  scale_factor_mask: 0.05           # Масштабный коэффициент для уменьшения маски перед применением алгоритма
  calibration_display_scale: 1.0   # Масштаб отображения окна калибровки
  working_display_scale: 4         # Коэффициент сжатия рабочей области при работе
  sharpening: 0                    # Применение фильтра повышения резкости к кадру (0 - без фильтра, 1 - с фильтром)
  online: 1                        # Настройка источника видео (0 - с видео, 1 - с камеры)
  video_path: 'video_photo_space\vid1.mp4'
  parallax: 0
  video_stream: 0                  # ID-камеры (при работе в режиме online = 1)

map_params:
  resolution: 2200                 # Размер поля (в мм)
  algorithm: "dijkstra"               # Выбор алгоритма поиска пути (astar/dijkstra/greedy/bdastar)
  dynamic_update: 0                # Режим обновления маршрута алгоритма (0 - статический маршрут, 1 - динамический)

  smoothing: 40                   # Расстояние упреждения точек для работы алгоритма (для реализации непрерывной езды)
  acceptable_error: 30             # Максимальная допустимая ошибка для остановки на целевой точке

robot:
  radius: 250                      # Радиус корпуса робота (в мм)
  max_speed: 0.08                  # Максимально допустимая линейная скорость робота (в м/с)

auto_mode:
  enable: 0                        # Автоматический режим (0 - движение через клики, 1 - движение через
  start_x: 1900                    # X-координата начальной точки (пиксели)
  start_y: 300                     # Y-координата начальной точки (пиксели)
  end_x: 300                       # X-координата конечной точки (пиксели)
  end_y: 1900                      # Y-координата конечной точки (пиксели)

spline:
  enable: 1                     # 1 – движение по сплайнам, 0 – обычный путь
  spline_step_mm: 10            # желаемое расстояние между соседними точками сплайна (мм)
  subsample_step: 10          # брать каждую 3-ю точку исходного пути A*